job('Maven_project'){
	description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven projects hosted on github")
	scm{
	   git('https://github.com/kiran1036999/G1.git','master')
	}
	
	triggers{
	   scm('* * * * *')
	}
	
	steps{
	   maven('clean package','sample_app_v1.0/pom.xml')
	}
	
	publishers{
		archiveArtifacts '**/*jar'
	}
}
